### PR TITLE
Add rich progress bars

### PR DESCRIPTION
**Pull request by brittonsmith**
## PR Summary

This implements a ytree-specific progress bar using `rich`. This is based heavily on the work of @neutrinoceros in [PR #3114](https://github.com/yt-project/yt/pull/3114) for yt. The main difference here is that I have implemented this as a context manager. If the pbar is not used as a context manager, I have found that KeyboardInterrupts and other exceptions are caught (at least when running with `-i`) and it is non-trivial to kill the session.

I've also taken the opportunity to transplant a couple yt utility functions here to avoid depending on yt for them.

## PR Checklist

- [ ] Code passes tests.
- [ ] New features are documented with docstrings and narrative docs.
- [ ] Tests added for fixed bugs or new features.

### CODE REVIEW

**Comment by neutrinoceros** [comment]
wow this is cool !
Feel free to give some feedback on the yt PR too, I'd like to take your suggestions into account but I don't want to have a discussion _here_ about the PR _there_.
Tell me if you need/want my review here, I'll happily take a moment to read through it :)

**Comment by neutrinoceros** [comment]
quick note: if you're never going to have more than a single task, you could maybe take some inspiration from the way `rich.progress.track` is implemented ? I don't know wether it retains the desirable traits from the context manager implementation you have here, but if it does, it means you can save an indentation level wherever you're using a pbar.

**Comment by brittonsmith** [comment]
@neutrinoceros, glad you like it! I am envisioning some more complex behavior in the future with multiple task bars, so I like the flexibility of using the pbar directly. Thanks again for the inspiration.

**Comment by brittonsmith** [comment]
As well, if you'd care to look at the implementation in `ytree/utilities/logger.py`, you are most welcome. The rest of the changes here are just threading it through, so feel free to ignore.

**Comment by neutrinoceros** [comment]
I'll review this today if I can manage!

**Comment by brittonsmith** [comment]
I've decided to put this on hold for now. I get strange behavior when I have a debugger inside a progress bar that is similar to what I saw when trying to end a process with a `KeyboardInterrupt` when using the progress bar not in a context manager. I don't really like how the output to the terminal is captured by rich in a way that is not always easy to get at.

**Pull request closed without merging**
